Rewrited what-is-conflux.md
Conflux-Chain/conflux-documentation pull request #100
Opened 2023-03-14 23:26 UTC by 0xn1c0

Added information about PoS and Spaces

2023-03-15 06:46 UTC, darwintree requested changes
The added information is generally good. But there is some problems on the original page 
 and so as the new page.

As an overview page of CONFLUX, this page is expected to present Conflux's highlights rather than technical implementation details. 

As far as I am concerned, there are 2 main highlights: 1) Its consensus. Conflux has a very high tps and will not sacrifice decentralization. 2) spaces: Conflux has 2 spaces - core space with internal sponsorship mechanism(make it possible for China mainland) and espace fully compatible with ethereum.

The authenticated storage and transaction relay protocol should be moved to another place for node developers.

2023-03-16 09:23 UTC, darwintree submitted a review, later dismissed

2023-03-16 09:41 UTC, darwintree approved these changes

2023-03-16 12:22 UTC, 0xn1c0 reviewed
Looks good. Is it ready to merge?

2023-03-17 01:53 UTC, darwintree approved these changes

2023-03-17 01:53 UTC, merged