Update accounts.md
Conflux-Chain/conflux-documentation pull request #161
Opened 2023-04-27 13:50 UTC by Euroanchor

fix: typo. Line 12 'slight' ---> 'slightly'
fix: typo. Line 64 'Comparations' ---> 'Comparisons'

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ ] **This is NOT a PR to submit translation**

2023-04-28 01:46 UTC, darwintree reviewed
lgtm! But it seems that the line 64 typo fix is not commited?

2023-05-05 14:07 UTC, 0xn1c0 approved these changes

2023-05-05 14:09 UTC, 0xn1c0 requested changes
There is a pending change:

fix: typo. Line 64 'Comparations' ---> 'Comparisons'

2023-06-29 13:39 UTC, 0xn1c0 approved these changes

2023-06-29 14:32 UTC, merged