Added Index Page
Conflux-Chain/conflux-documentation pull request #230
Opened 2023-10-30 15:11 UTC by 0xn1c0

## Pre-flight checklist

- [ x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x ] **This is NOT a PR to submit translation**

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/230)

2023-10-31 02:13 UTC, darwintree requested changes
I think simply summarize the structure is not enough. I think we are supposed to pick up the most important articles. We can later discuss it on the meeting

2023-11-01 02:21 UTC, darwintree requested changes
1. I think summary should be added to each section to conclude why this section is selected and what does the article say. 
2. I think we need to slightly change the article and introduction as this is somewhat not the index but the minimum knowledge developers would need to know (especially for core developers)

2023-11-01 14:10 UTC, 0xn1c0 commented
I just committed the changes based on your suggestions

2023-11-15 01:40 UTC, darwintree approved these changes

2023-11-15 01:41 UTC, merged