add how to upgrade node
Conflux-Chain/conflux-documentation pull request #334
Opened 2023-12-26 09:52 UTC by Pana

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ ] **This is NOT a PR to submit translation**

2023-12-26 10:34 UTC, darwintree requested changes

2023-12-26 10:34 UTC, darwintree commented on docs/general/run-a-node/run-a-node.md
>  Make sure to keep your Conflux node software updated to the latest version to ensure compatibility with the network and to include the latest features and security patches.
Better to add 
```suggestion
Make sure to [keep your Conflux node software updated](./how-to-upgrad.md) to the latest version to ensure compatibility with the network and to include the latest features and security patches.
```

2023-12-26 10:34 UTC, darwintree commented on docs/general/run-a-node/run-a-node.md
> +* Linux XFS file system is performance but not stable, **ext4 is recommended**.
```suggestion
* While the Linux XFS file system offers performance benefits, it is not as stable; therefore, **ext4 is recommended** for its reliability and stability.
```

2023-12-26 22:22 UTC, 0xn1c0 approved these changes

2023-12-28 07:01 UTC, darwintree approved these changes

2023-12-28 07:01 UTC, merged