add Conflux Scaffold Documentation
Conflux-Chain/conflux-documentation pull request #425
Opened 2024-03-02 03:27 UTC by intrepidcanadian

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ ] **This is NOT a PR to submit translation**

2024-03-04 03:41 UTC, darwintree requested changes
Than you for your pull request. This is really an awesome pull request! However, some changes are required before merging.

1. Removing the lock file and `.yarn` cache files as well as `.yarnrc.yml`. These files are not needed for the new contents for document building.
2. Changing the network abbreviation to make it same as in viem definition (already suggested in document files but more changes are needed in scaffold project file)
3. Would you mind transferring the repo to conflux-fans? In that way we could maintain the repo for the following up security patches or requested new features.
4. This is not requested change but I think adding it would be better: how to change the configuration of an existed projects created from scaffold-eth to make it support conflux espace. This could serve as a individual issue and pull request.

2024-03-04 03:41 UTC, darwintree commented on docs/espace/tutorials/scaffoldCfx/scaffold.md
> +yarn deploy --network ConfluxEspace
This network configuration is defined in hardhat. I suggest the network definition would be better to be consistent with viem definition

```suggestion
yarn deploy --network confluxESpace
```

2024-03-04 03:41 UTC, darwintree commented on docs/espace/tutorials/scaffoldCfx/scaffold.md
> +yarn deploy --network ConfluxEspaceTest
This network configuration is defined in hardhat. I suggest the network definition would be better to be consistent with viem definition

```suggestion
yarn deploy --network confluxESpaceTest
```

2024-03-04 03:41 UTC, darwintree commented on docs/espace/tutorials/scaffoldCfx/scaffold.md
> +targetNetworks: [chains.confluxEspace]
```suggestion
targetNetworks: [chains.confluxESpace]
```

2024-03-04 03:41 UTC, darwintree commented on docs/espace/tutorials/scaffoldCfx/scaffold.md
> +yarn deploy --network confluxEspaceTest
This network configuration is defined in hardhat. I suggest the network definition would be better to be consistent with viem definition

```suggestion
yarn deploy --network confluxESpaceTest
```

2024-03-04 21:00 UTC, intrepidcanadian commented on package-lock.json
Removed

2024-03-04 21:00 UTC, intrepidcanadian commented on yarn.lock
Removed

2024-03-04 21:20 UTC, intrepidcanadian commented on docs/espace/tutorials/scaffoldCfx/scaffold.md
> +git clone https://github.com/intrepidcanadian/conflux-scaffold
can you help with giving me permission to transfer? When I try to transfer to conflux-fans, I get the following message

"You don’t have the permission to create public repositories on conflux-fans"

2024-03-04 21:28 UTC, intrepidcanadian commented
Thanks for reviewing and the suggestions! I think I am just missing moving over the repo to conflux-fans once you provide me permission to create a public repo on conflux-fans and then I can change the git clone SSH link in the instructions

Thanks!

2024-03-05 02:25 UTC, darwintree commented
I've figured out a workaround that a repo is created from scratch and I've invited you as a maintainer: https://github.com/conflux-fans/conflux-scaffold.
Except for this change, I think you've misunderstood the repo to remove the build files. It seems build files are removed from conflux-scaffold (but should removed from **conflux-documentation**!). I think you need to do the following operation:

```
git rm -r .yarn
git rm package.lock .yarnrc.yml
```

and restoring `yarn.lock`

2024-03-05 05:35 UTC, intrepidcanadian commented
> I've figured out a workaround that a repo is created from scratch and I've invited you as a maintainer: https://github.com/conflux-fans/conflux-scaffold. Except for this change, I think you've misunderstood the repo to remove the build files. It seems build files are removed from conflux-scaffold (but should removed from **conflux-documentation**!). I think you need to do the following operation:
> 
> ```
> git rm -r .yarn
> git rm package.lock .yarnrc.yml
> ```
> 
> and restoring `yarn.lock`

Okay! I think I have made the changes requested above. I have removed package-lock, yarmrc.yml and .yarn. Also have restored yarn.lock. I have also re-adjusted the url for the repos to reflect the url of the repo in conflux-fans

2024-03-05 05:57 UTC, darwintree commented
> > I've figured out a workaround that a repo is created from scratch and I've invited you as a maintainer: https://github.com/conflux-fans/conflux-scaffold. Except for this change, I think you've misunderstood the repo to remove the build files. It seems build files are removed from conflux-scaffold (but should removed from **conflux-documentation**!). I think you need to do the following operation:
> > ```
> > git rm -r .yarn
> > git rm package.lock .yarnrc.yml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and restoring `yarn.lock`
> 
> Okay! I think I have made the changes requested above. I have removed package-lock, yarmrc.yml and .yarn. Also have restored yarn.lock. I have also re-adjusted the url for the repos to reflect the url of the repo in conflux-fans

From the commit history, It seems the yarn.lock is not restored in the latest 2 commits. Would you recheck it?

2024-03-05 06:17 UTC, darwintree approved these changes

2024-03-05 06:37 UTC, merged