update general/conflux-basics/gas.md, regarding the issue #451
Conflux-Chain/conflux-documentation pull request #453
Opened 2024-03-13 07:42 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] **This is NOT a PR to submit translation**

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/453)

2024-03-13 09:21 UTC, darwintree requested changes
Thank you for your pull request. There are some changes needed before this pull request could get merged.

1. The position where the content is inserted. Currently the new part is inserted into between `How gasFee is calculated` and the subsection `gasUsed`. It is supposed to move somewhere else to retain context consistency
    <img width="333" alt="image" src="https://github.com/Conflux-Chain/conflux-documentation/assets/17946284/a0473959-cc81-4a69-8f94-8baed7266933">
2. the second point and third point are referring the same thing ---- sponsorship mechanism. And I don't think this is the suitable contents here. From the user's perspective, he has hardly choice making use of the sponsorship mechanism or not. And from developers' perspective, the developer did not pay less.
3. The header "How do I pay less gas?" should be changed. For example, "How can users pay less gas fee?". And relating contents can be illustrated from user's or developer's perspective, for example, optimizing contract logic, using multicall, etc

2024-03-13 10:18 UTC, jackleeio commented
Made some changes as per your tips

2024-03-14 02:45 UTC, darwintree commented
> Made some changes as per your tips

The modified content is good! And for the current content, I think it would be better to be listed as an individual article because the pages in `general/conflux-basics` folder will mainly focus on general concepts rather than detailed development guide. You can move the gas optimization suggestion to create a new page in general/build/contracts as you suggested in #454. Then you can link the new page in this page.

Another question is the *a series of tutorials* for gas optimization. I guess you are going to create detailed tutorials, for example, illustrate the mechanism and giving an example on how to use libraries. In that case that would be awesome. But it is also a choice that you only contain the most important key points in a single article. But anyway it depends on you.

2024-03-14 08:16 UTC, darwintree commented
I think after the above minor change, the current content is ready to be merged. Would you like to be merged immediately or after all the relating gas optimization tutorials are ready?

2024-03-14 08:21 UTC, jackleeio commented on docs/general/build/smart-contracts/introduction-to-smart-contracts.md
> +# displayed_sidebar: generalSidebar
Got it

2024-03-14 08:22 UTC, darwintree approved these changes
lgtm

2024-03-14 08:28 UTC, jackleeio commented
thanks, bro

2024-03-14 08:29 UTC, merged