Update network-endpoints.md
Conflux-Chain/conflux-documentation pull request #485
Opened 2024-03-27 02:29 UTC by intrepidcanadian

to clarify - it confused me why the testnet api key was not working when i attached the api key to the espace mainnet rpc

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ ] A relating issue is created: # (<- fill the issue number here)
- [ ] **This is NOT a PR to submit translation**

2024-03-27 06:45 UTC, darwintree requested changes
Thank you for the pull request! The mainnet and testnet api key are different because we would like developers to be able to purchase testnet api key freely(by using testnet CFX or testnet USDT). Sorry for that we did not mention it in our documentation

2024-03-27 06:45 UTC, darwintree commented on docs/espace/network-endpoints.md
> +- Append your api key(get from [Web3 Paywall](../general/build/tools/web3paywall.md) or Conflux Foundation) to the endpoint for privileged access (eg., `https://evm.confluxrpc.com/<api-key>` or for t
```suggestion
- Append your api key(get from [Web3 Paywall](../general/build/tools/web3paywall.md) or Conflux Foundation) to the endpoint for privileged access (eg., `https://evm.confluxrpc.com/<mainnet-api-key>` or for testnet, `https://evmtestnet.confluxrpc.org/<testnet-api-key>`);
```

2024-03-27 12:43 UTC, intrepidcanadian reviewed
yes that makes sense to have that clarification

2024-03-28 01:32 UTC, darwintree approved these changes

2024-03-28 01:32 UTC, merged