Refs #476 -- Added tutorials for using WalletConnect in Next.js project
Conflux-Chain/conflux-documentation pull request #532
Opened 2024-04-14 13:49 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #476  (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

2024-04-16 02:28 UTC, darwintree requested changes
Several changes are requested. Besides, a relating repo is created (https://github.com/conflux-fans/web3modal-conflux-nextjs) with vercel deployments.

2024-04-16 10:00 UTC, jackleeio commented
> Several changes are requested. Besides, a relating repo is created (https://github.com/conflux-fans/web3modal-conflux-nextjs) with vercel deployments.

A related project already exists, we created it a few days ago（https://github.com/ConfluxDAO/web3modal-conflux-nextjs)

2024-04-16 10:40 UTC, jackleeio commented on docs/espace/tutorials/walletConnect/nextjs.md
> +
already added

2024-04-16 10:41 UTC, jackleeio commented on docs/espace/tutorials/walletConnect/nextjs.md
> +export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;
already added

2024-04-17 03:19 UTC, darwintree commented
> > Several changes are requested. Besides, a relating repo is created (https://github.com/conflux-fans/web3modal-conflux-nextjs) with vercel deployments.
> 
> A related project already exists, we created it a few days ago（https://github.com/ConfluxDAO/web3modal-conflux-nextjs)

That's great. Then I would suggest the repo link be added to the article as well as the vercel builds for online preview

2024-04-18 01:49 UTC, merged