Refs #510 -- Added content to CRC721 NFT Tutorial
Conflux-Chain/conflux-documentation pull request #552
Opened 2024-04-21 12:34 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #510 (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

2024-04-23 08:51 UTC, darwintree requested changes
Except for the mentioned issues, example code relating to sponsorship is supposed to added

2024-04-23 08:51 UTC, darwintree commented on docs/core/tutorials/nft-tutorials/crc721.md
> +  const tokenURI = "https://yourdomain.com/metadata/1.json"; // The metadata URI for the NFT
It is quite hard to configure a token URI from scratch. Would suggest to provide a template toke uri here
```suggestion
  const tokenURI = "https://raw.githubusercontent.com/conflux-fans/dual-space-nft-metadata/main/2023040104"; //  Replace the example tokenURI with the actual metadata URI for the NFT
```

2024-04-23 13:15 UTC, jackleeio commented
I think the contract sponsorship part is optional, and there are some tutorials on how to get contract sponsorship.

2024-04-24 02:21 UTC, darwintree approved these changes

2024-04-24 02:21 UTC, merged