Refs #509 -- Added a tutorial to introduce how to cross-space CRC20 token to eSpace
Conflux-Chain/conflux-documentation pull request #592
Opened 2024-05-16 08:33 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #509 (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

2024-05-17 09:43 UTC, darwintree requested changes
I think current version needs refactoring. As previously discussed, this article mainly serve as a **tutorial** for how to register the token and enable core space erc20 token bridging to espace, which means, the internal implementation is not important and will interfere the article's readability. The contract imlementation illustration can be put into the planned article on `CrossSpaceCall` explanation

How to modify:

1. (use the cofluxscan contract view) just focus on the operation with simple illustration. Then this article can be moved into the tutorial folder. Or
2. directly providing js/python scripts on the operation.

The difference depends on the target audience

2024-05-20 07:08 UTC, darwintree requested changes

2024-05-20 07:08 UTC, darwintree commented on docs/core/build/cross-space/crc20-cross-space.md
> +This tutorial guides developers on transferring any CRC20 token from Core Space to eSpace, using [FansCoin (FC)](https://confluxscan.io/token/cfx:achc8nxj7r451c223m18w2dwjnmhkd6rxawrvkvsy2) as an exa
Using FC as example seems improper here as the main content of this article is now how to enable token transfer.

2024-05-24 08:54 UTC, jackleeio commented
Are there any other issues? @darwintree

2024-05-24 10:16 UTC, darwintree commented
> Are there any other issues? @darwintree

Apologies for the delay in reviewing the recent articles. Our current focus is on addressing issues related to the upcoming Conflux hard fork. We estimate that the most urgent tasks will be completed by the end of next week, though it could take longer. We appreciate your patience if we are unable to review the recent pull requests in the coming days.

2024-06-06 09:16 UTC, darwintree requested changes
This article is moved to the tutorial folder, and should be considered as a normal-user-oriented article.

1. For most users, the step `sing the Official Cross-Space Bridge` is enough. It is recommended to place it to the first place.
2. If the token bridging is not applicable (not registered before), then reader can then check the currrent step 1 and 2 to register token and create token mapping
3. Recommeded to remove current step 4 and 5 as currently this is enough for users, for example, if he or she would like to add liquidity to swappi. However, it is still acceptable if you would like to add relating content, but current version is not appropriate. For developers, it is a more reliable and authentic way to show how to modify the parameter in https://github.com/Conflux-Chain/conflux-dapps to deploy a fork version of the frontend

2024-06-11 04:26 UTC, jackleeio commented
This tutorial is clearly intended for developers. It is not suitable for most ordinary users, as their needs are completely different from the topic of this article. It’s unlikely that non-developers will be issuing a token and crossing space to eSpace.

For your first point, I recommend creating a simpler tutorial based on the Step 3 extension, rather than changing the existing structure.

Regarding the third point, as I mentioned before, this is an issue developers will likely encounter when their project issues a token and needs to cross space to eSpace.

2024-06-11 09:25 UTC, darwintree requested changes

2024-06-11 09:25 UTC, darwintree commented on docs/core/tutorials/crc20-cross-space.md
> +You can also visit the community-deployed version at [community cross-space bridge](https://bridge.fanscoin.org), or submit a PR at this [repository](https://github.com/ConfluxDAO/conflux-evm-bridge/
```suggestion
The frontend code of ConfluxHub is hosted at [conflux-dapps](https://github.com/Conflux-Chain/conflux-dapps). You can also customize your own version of token list as you wish by modifying the parameter [innerTokenListUrl(in dapps/cross-space/src/components/TokenList/tokenListStore.ts)](https://github.com/Conflux-Chain/conflux-dapps/blob/dev/dapps/cross-space/src/components/TokenList/tokenListStore.ts) and then deploy it.
```

2024-06-12 01:30 UTC, darwintree approved these changes

2024-06-12 01:30 UTC, merged