Refs #454 -- Added multicall-in-router.md to general/build/smart-contracts/gas-optimization
Conflux-Chain/conflux-documentation pull request #619
Opened 2024-06-14 16:12 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #454 (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

2024-06-18 02:53 UTC, darwintree requested changes
I'm not familiar with this approach and I would wonder how much it can be saved to use multicall. From my institution I think not much can be saved.

Another improvement is that the multicall contract address can be found [here](https://doc.confluxnetwork.org/docs/espace/build/deployed-contracts)

2024-06-24 07:02 UTC, jackleeio commented
The gas savings depend on the complexity of the functions and use cases. In simpler examples, like the ones in my initial demo code, the savings are less apparent due to basic operations and the overhead of multicall itself. Therefore, multicall's loop and result handling overhead are more pronounced.

However, in real-world scenarios, such as with Uniswap Router and Compound Bulker, multicall batches complex operations into a single transaction, significantly reducing gas costs.

2024-06-27 03:01 UTC, darwintree commented
> The gas savings depend on the complexity of the functions and use cases. In simpler examples, like the ones in my initial demo code, the savings are less apparent due to basic operations and the overhead of multicall itself. Therefore, multicall's loop and result handling overhead are more pronounced.
> 
> However, in real-world scenarios, such as with Uniswap Router and Compound Bulker, multicall batches complex operations into a single transaction, significantly reducing gas costs.

That makes sense but without some specific data this pr might not be merged from my end

2024-06-28 02:53 UTC, darwintree approved these changes

2024-06-28 02:53 UTC, merged