Add Security Advice for Creating a Wallet
Conflux-Chain/conflux-documentation pull request #695
Opened 2024-08-14 11:17 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #684  (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/695)

2024-08-16 02:40 UTC, darwintree requested changes
I think the general idea content is good. But current version is not good enough for blockchain beginners as too many details are not presented in this article although they seem to be common knowledge.

I suggest adding more details to the article

2024-08-16 02:40 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +A blockchain wallet is essentially a tool for managing your private keys. The private key is a randomly generated string of numbers, while the mnemonic phrase is a human-readable version of the priva
This is not accurate. Mnemonic is human-readable version of random seed and private key can be derived from it

2024-08-16 02:40 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +Remember: Whoever holds the private key controls the assets in the wallet.
```suggestion
Remember: Whoever holds the private key controls the assets in the wallet, so never tell it to anyone else or expose it on Internet.
```

2024-08-16 02:40 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +There are various wallet types, including:
I suppose more introduction or relating articles should be added to this section. I would suppose the reader be a beginner of blockchain world and current version would make it hard for reader to understand

2024-08-16 02:40 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +
Add details illustrating why this strategy is required

2024-08-16 02:40 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +## 6. Understanding Emerging Keyless Wallet Technology
More details are needed here

2024-08-16 02:40 UTC, darwintree commented on docs/espace/tutorials/oracle/Witnet/_category_.json
> +{
should be removed

2024-08-16 02:40 UTC, darwintree commented on docs/espace/tutorials/oracle/Witnet/randomNumbers.md
> +---
should be removed

2024-08-16 15:12 UTC, jackleeio commented
Updated based on feedback

2024-08-19 02:32 UTC, darwintree requested changes

2024-08-19 02:32 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +There are various wallet types, including:
Should add "what this is" as well as "what it is used for"

2024-08-19 02:33 UTC, darwintree requested changes

2024-08-19 02:33 UTC, darwintree commented on docs/general/blockchain-security/create-wallet.md
> +1. **Random Seed**: This is a large, randomly generated number that serves as the foundation of your wallet. It's the most crucial piece of information.
What does this mean?

2024-08-19 09:05 UTC, darwintree approved these changes

2024-08-19 09:05 UTC, merged