Add Using Vanity Address to gas optimization
Conflux-Chain/conflux-documentation pull request #753
Opened 2024-10-12 00:22 UTC by jackleeio

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #454  (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

2024-10-14 18:24 UTC, 0xn1c0 requested changes
I left a comment with a requested change. Except for that, all rest is good.

2024-10-14 18:24 UTC, 0xn1c0 commented on docs/general/build/smart-contracts/gas-optimization/useVanityAddress.md
> +    const saltHex = ethers.zeroPadValue(ethers.hexlify(salt), 32);
I had issues on this line here when running the code, i had to change ethers.hexlify(salt) to ethers.toBeHex(salt) for compatibility with the latest ethers.js version.
I suggest replacing this line for:
`const saltHex = ethers.zeroPadValue(ethers.toBeHex(salt), 32);`

2024-10-18 14:00 UTC, iamxyzxyz approved these changes

2024-10-18 14:02 UTC, 0xn1c0 approved these changes

2024-10-18 14:03 UTC, merged